services:
  NLP_ENV:
    container_name: NLP_ENV
    build:
      context: .
      dockerfile: Dockerfile
    image: nlp_env:latest
    ports:
      - "8888:8888"
    # To keep the container running and allow interactive sessions:
    # Not really needed since I'll be running Jupyter Notebook.
    #stdin_open: true
    volumes:
      - ./:/app